# https://gist.github.com/667693
package_path: assets # (defaults to assets)
gzip_assets: off # (on off)

javascripts:
  all:
    - public/javascripts/jquery.js
    - public/javascripts/jquery.anchor.js
    - public/javascripts/jquery.scroll.js
    - public/javascripts/jquery.current.js
    - public/javascripts/raphael.js
    - public/javascripts/icons.js
    - public/javascripts/application.js

stylesheets:
  all:
    - tmp/reset.css
    - tmp/layout.css
    - tmp/style.css
